name: Build and push

on:
  push:
    branches:
      -main
      -master

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    - name: Checkout code
      Uses: actions/checkout@v4

    - name: setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version:21
        distribution:'temurin'
    
    - name: Build WAR file
      run: mvn clean package
    
    - name: Setup Docker buildx
      run: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push to dockerhub
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: janakniroula/simple-webapp:latest